[project]
name = "pydex"
version = "2.0"
description = "Pydex for Python functions and standard libraries"
requires-python = ">=3.13"
authors = [
    { name = "Meobanh" }
]
dependencies = [
    "beautifulsoup4",
    "groq",
    "psycopg2-binary",
    "python-dotenv",
    "requests",
    "rich",
]

[project.scripts]
pydex = "main:main"

[tool.setuptools]
py-modules = ["db", "load_data", "main", "scan_file", "scrape_builtins", "extract_stdlib", "commands"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"