[project]
name = "pydex"
version = "2.0"
description = "CLI tool for exploring and mastering Python standard libraries."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Meobanh" }
]
dependencies = [
    "rich",
]

[project.optional-dependencies]
dev = [
    "beautifulsoup4",
    "groq",
    "requests",
]

[project.scripts]
pydex = "main:main"

[tool.setuptools]
py-modules = ["main", "commands", "scan_file", "db"]

[tool.setuptools.package-data]
"*" = ["seed.sql"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"